[GLOBAL]
pants_version = "2.16.0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.isort",
]

[source]
root_patterns = [
    "/src/python",
    # "src/python/api",
    # "src/python/common"
    "/tests"
]

[anonymous-telemetry]
enabled = true
repo_id = "55e350b1-b251-4bc2-bd52-5a9ac30d2440"

[python]
enable_resolves = true
interpreter_constraints = ["==3.10.*"]
